Header with Burger menu
PL-FE-MAY23-CodeCrusaders/product_catalog pull request #3
Opened 2023-10-30 11:41 UTC by szymonpachucki

2023-10-30 18:44 UTC, HaniaNassalska requested changes

2023-10-30 18:44 UTC, HaniaNassalska commented on src/components/header/Header.scss
'npm install sass' is necessary. Without it, the project won't start ;)
This is not SASS ;) This is not a valid BEM. I would also make separate files for .header and .nav.

2023-10-30 18:44 UTC, HaniaNassalska commented on src/components/header/Header.tsx
RWD - there is a problem with the size below 520px. The font is also bad on smaller screens.

2023-11-02 08:17 UTC, szymonpachucki commented
@HaniaNassalska @Capoverde @lOdwrotMail

2023-11-02 14:35 UTC, szymonpachucki commented
fixed json problem @HaniaNassalska @Capoverde @lOdwrotMail

2023-11-02 19:17 UTC, HaniaNassalska requested changes
You're not using NavLinks, paths need fixing. Still an issue with RWD. CSS needs a bit more improvement. All according to our conversation :) We're getting closer - it's already looking nice.

2023-11-03 12:59 UTC, pawel-peksa commented on src/cart/cart.scss
> +@media screen and (min-width: 641px) and (max-width: 1199px) {
Breakpoint should be set to 650
```suggestion
@media screen and (min-width: 650px) and (max-width: 1199px) {
```

2023-11-04 11:15 UTC, pawel-peksa requested changes
Please resolve merge conflicts

2023-11-06 18:55 UTC, HaniaNassalska approved these changes

2023-11-06 18:56 UTC, merged