Card
PL-FE-MAY23-CodeCrusaders/product_catalog pull request #9
Opened 2023-11-01 21:05 UTC by Capoverde

pls check this component

2023-11-02 08:57 UTC, HaniaNassalska requested changes
You made changes on the old main branch. Please update it to the new one - without this update, we will have a significant mess when you merge it to the main branch. You should merge the new main branch into this branch (in VSC, when you are on the Card branch - use 'git merge main'), and after that, I will check it - currently, I can't even open it.

2023-11-04 11:16 UTC, pawel-peksa requested changes
Please resolve merge conflicts

2023-11-06 18:49 UTC, HaniaNassalska approved these changes

2023-11-06 18:55 UTC, pawel-peksa approved these changes

2023-11-06 19:55 UTC, merged